### ISSUE TITLE
**AWS DynamoDB - Dynamo-Crud setup**

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#22]
- [ ] #23 for usermans dynamodb credential

- [ ] #24 read DynamoDB AWS documentation

- [ ] #24 read and understand DynamoDB API documentation

- [ ] #24 pip install dynamo-crud

- [ ] #25 using the usermans cert, create or update a user data table in DynamoDB
