### ISSUE TITLE
[FEATURE] Email Validation

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#228]
**Explanation**
This is a feature tracker for email validation.  This feature will implement email validation for new user registration

**Brief**
This is a multi task feature that will implement ORM and email validation scripts that will validate new user email addresses.

**Outline**
- [x] Update User ORM to have validated, validation code, and validation date
- [x] Implement a script for sending email.  setup script in app.util.mail
- [x] verified users will be added into the user role

**Child Issues**
- [x] #229 
- [x] #230 
- [x] #231 
- [x] #232
- [x] #233 

**Additional context**
