### ISSUE TITLE
**UI/UX Master**

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pie#32]
Primary UI/UX front end tracking ticket for all front-end issues and tasks.

- [ ] Submit desired work schedule and availability in a tracking issue ticket and post it in this issue
- [x] #1
- [x] #3
- [x] #2
- [x] #13
- [x] #33
- [x] Schedule call with @stuart909 to go over front-end Jinja / Flask dev
- [x] Conduct training with @stuart909 
- [x] #34 Create HTML template / Jinja 
- [ ]  #37

**Comment by bmeissn2** [comment]
Hey Jasmine can you give me an update on the status?

**Comment by jmm28** [comment]
Sorry for the late response! I'm still working on the profile pages and blog posts. Experimenting a bit with architecture.
